version: '3.8'

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - clip
      - sam
  clip:
    build: ./clip
    container_name: clip
    ports:
      - "5001:5001"
  sam:
    build: ./sam
    container_name: sam
    ports:
      - "5002:5002"
